In [1]:
import pandas as pd
import matplotlib.pyplot as plot
import csv

In [2]:
df_0 = pd.read_csv('.\\data\\daily_sales_data_0.csv')
df_1 = pd.read_csv('.\\data\\daily_sales_data_1.csv')
df_2 = pd.read_csv('.\\data\\daily_sales_data_2.csv')

In [3]:
# df_0.head()
# df_1.head()
df_2.head()

       product  price  quantity        date region
0  pink morsel  $3.00       526  2020-10-13  north
1  pink morsel  $3.00       546  2020-10-13  south
2  pink morsel  $3.00       505  2020-10-13   east
3  pink morsel  $3.00       561  2020-10-13   west
4  gold morsel  $9.99       553  2020-10-13  north

<h3> to get the idea of data types of each column

In [4]:
df_0.info()
df_1.info()
df_2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13720 entries, 0 to 13719
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   13720 non-null  object
 1   price     13720 non-null  object
 2   quantity  13720 non-null  int64
 3   date      13720 non-null  object
 4   region    13720 non-null  object
dtypes: int64(1), object(4)
memory usage: 536.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13720 entries, 0 to 13719
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   13720 non-null  object
 1   price     13720 non-null  object
 2   quantity  13720 non-null  int64
 3   date      13720 non-null  object
 4   region    13720 non-null  object
dtypes: int64(1), object(4)
memory usage: 536.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13720 entries, 0 to 13719
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   product   13720 non-null  object
 1   price     13720 non-null  object
 2   quantity  13720 non-null  int64
 3   date      13720 non-null  object
 4   region    13720 non-null  object
dtypes: int64(1), object(4)
memory usage: 536.1+ KB

<h3> Types of product & count

In [5]:
df_0['product'].value_counts()

product
pink morsel          1960
gold morsel          1960
magenta morsel       1960
chartreuse morsel    1960
periwinkle morsel    1960
vermilion morsel     1960
lapis morsel         1960
Name: count, dtype: int64

<h3> Filter out by 'pink morsel' only, 
<h3> then save it in csv same file

In [6]:
df_0 = df_0[df_0['product'] == 'pink morsel']
df_0.to_csv('.\\data\\processed_data_0.csv', index=False)

In [7]:
df_0.head()

        product  price  quantity        date region
0   pink morsel  $3.00       546  2018-02-06  north
1   pink morsel  $3.00       549  2018-02-06  south
2   pink morsel  $3.00       577  2018-02-06   east
3   pink morsel  $3.00       519  2018-02-06   west
28  pink morsel  $3.00       529  2018-02-07  north

<h3> similarly filter out for df_1 and df_2

In [8]:
df_1 = df_1[df_1['product'] == 'pink morsel']
df_1.to_csv('.\\data\\processed_data_1.csv', index=False)

df_2 = df_2[df_2['product'] == 'pink morsel']
df_2.to_csv('.\\data\\processed_data_2.csv', index=False)

In [9]:
df_1.head()

        product  price  quantity        date region
0   pink morsel  $3.00       545  2019-06-11  north
1   pink morsel  $3.00       521  2019-06-11  south
2   pink morsel  $3.00       595  2019-06-11   east
3   pink morsel  $3.00       507  2019-06-11   west
28  pink morsel  $3.00       576  2019-06-12  north

In [11]:
df_2.head()

        product  price  quantity        date region
0   pink morsel  $3.00       526  2020-10-13  north
1   pink morsel  $3.00       546  2020-10-13  south
2   pink morsel  $3.00       505  2020-10-13   east
3   pink morsel  $3.00       561  2020-10-13   west
28  pink morsel  $3.00       560  2020-10-14  north

<h3> Add new column name "sales" and sales = price * product.
<h3> But direct multiplication is not possible as price has '$' sign and datatype is str.
<h3> So, need to convert to str 2st then replacing '$' with '' & then converting it to float.

In [12]:
df_0['sales'] = df_0['price'].str.replace('$', '', regex=False).astype(float) * df_0['quantity']

In [13]:
df_0.head()

        product  price  quantity        date region   sales
0   pink morsel  $3.00       546  2018-02-06  north  1638.0
1   pink morsel  $3.00       549  2018-02-06  south  1647.0
2   pink morsel  $3.00       577  2018-02-06   east  1731.0
3   pink morsel  $3.00       519  2018-02-06   west  1557.0
28  pink morsel  $3.00       529  2018-02-07  north  1587.0

<h3> dropping 'price' & 'quantity' cols

In [14]:
df_0.drop(columns=['price', 'quantity'], inplace=True)

In [15]:
df_0

           product        date region   sales
0      pink morsel  2018-02-06  north  1638.0
1      pink morsel  2018-02-06  south  1647.0
2      pink morsel  2018-02-06   east  1731.0
3      pink morsel  2018-02-06   west  1557.0
28     pink morsel  2018-02-07  north  1587.0
...            ...         ...    ...     ...
13667  pink morsel  2019-06-09   west  1797.0
13692  pink morsel  2019-06-10  north  1698.0
13693  pink morsel  2019-06-10  south  1689.0
13694  pink morsel  2019-06-10   east  1623.0
13695  pink morsel  2019-06-10   west  1767.0

[1960 rows x 4 columns]

<h3> saving the data in same csv file for "df_0".

In [16]:
df_0.to_csv('.\\data\\processed_data_0.csv', index=False)

In [19]:
df_0.head()
df_0.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 13695
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   product  1960 non-null   object
 1   date     1960 non-null   object
 2   region   1960 non-null   object
 3   sales    1960 non-null   float64
dtypes: float64(1), object(3)
memory usage: 76.6+ KB

In [ ]:
# df_1 = pd.read_csv('.\\data\\daily_sales_data_1.csv')
# df_2 = pd.read_csv('.\\data\\daily_sales_data_2.csv')

<h3> repeating same procedure for "df_1" & "df_2"

In [20]:
df_1['sales'] = df_1['price'].str.replace('$', '', regex=False).astype(float) * df_1['quantity']
df_2['sales'] = df_2['price'].str.replace('$', '', regex=False).astype(float) * df_2['quantity']

df_1.drop(columns=['price', 'quantity'], inplace=True)
df_2.drop(columns=['price', 'quantity'], inplace=True)

df_1.to_csv('.\\data\\processed_data_1.csv', index=False)
df_2.to_csv('.\\data\\processed_data_2.csv', index=False)

In [24]:
df_1.head()
df_2.head()
df_1.info()
df_2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 13695
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   product  1960 non-null   object
 1   date     1960 non-null   object
 2   region   1960 non-null   object
 3   sales    1960 non-null   float64
dtypes: float64(1), object(3)
memory usage: 76.6+ KB
<class 'pandas.core.frame.DataFrame'>
Index: 1960 entries, 0 to 13695
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   product  1960 non-null   object
 1   date     1960 non-null   object
 2   region   1960 non-null   object
 3   sales    1960 non-null   float64
dtypes: float64(1), object(3)
memory usage: 76.6+ KB

<h3> now merging all 3 csv files

In [25]:
merged = pd.concat([df_0, df_1, df_2], ignore_index=True)
merged.to_csv('.\\data\\merged_processed_data.csv', index=False)

In [26]:
# merged.info()
merged.value_counts

<bound method DataFrame.value_counts of           product        date region   sales
0     pink morsel  2018-02-06  north  1638.0
1     pink morsel  2018-02-06  south  1647.0
2     pink morsel  2018-02-06   east  1731.0
3     pink morsel  2018-02-06   west  1557.0
4     pink morsel  2018-02-07  north  1587.0
...           ...         ...    ...     ...
5875  pink morsel  2022-02-13   west  2390.0
5876  pink morsel  2022-02-14  north  2035.0
5877  pink morsel  2022-02-14  south  2465.0
5878  pink morsel  2022-02-14   east  2500.0
5879  pink morsel  2022-02-14   west  2115.0

[5880 rows x 4 columns]>

<h3> merging all 3 CSV files on quantity and date data.

In [30]:
df_0_qua = pd.read_csv('.\\data\\daily_sales_data_0.csv')
df_1_qua = pd.read_csv('.\\data\\daily_sales_data_1.csv')
df_2_qua = pd.read_csv('.\\data\\daily_sales_data_2.csv')

In [31]:
merged_2 = pd.concat([df_0_qua[['date', 'quantity']], df_1_qua[['date', 'quantity']], df_2_qua[['date', 'quantity']]], ignore_index=True)

In [32]:
merged_2.to_csv('.\\data\\merged_quantity_data.csv', index=False)

In [33]:
merged_2.head()

         date  quantity
0  2018-02-06       546
1  2018-02-06       549
2  2018-02-06       577
3  2018-02-06       519
4  2018-02-06       580